### ISSUE TITLE
Slides in the book are not loading

### ISSUE THREAD

**Issue by hanneoberman** [UtrechtUniversity/workshop-computational-reproducibility#39]
E.g. on this page: https://utrechtuniversity.github.io/workshop-computational-reproducibility/introduction.html

![image](https://github.com/UtrechtUniversity/workshop-computational-reproducibility/assets/38891540/fe651aba-73b0-4980-a7c9-da3f14a2c290)

**Comment by nehamoopen** [comment]
Hi @hanneoberman, this will be fixed soon! We just switched all our workshop materials from `bookdown` to `quarto` and we didn't place the slides in the right path. Thanks for the heads up, we're on it ;)

**Comment by nehamoopen** [comment]
This should be fixed now!
