### ISSUE TITLE
Possible to copy/place this to/on GitLab

### ISSUE THREAD

**Issue by laurensstoop** [UtrechtUniversity/workshop-computational-reproducibility#6]
GitHub is nice, but has maaaany issues and worries associated. There is a GitLab available within the university.

**Comment by laurensstoop** [comment]
Link to the GitLab of science: [git.science.uu.nl](url)

**Comment by Danny-dK** [comment]
Aside from GitLab having Dutch roots, so far not having #metoo issues (that GitHub may have had before MS took it over), is not taken over by Microsoft, and has a lot more private repo availability (all already reasons why I like GitLab), I don't know of any technical reasons if there are any. If someone could share those, it would benefit my own knowledge (I already prefer to use GitLab).

**Comment by jelletreep** [comment]
UU has now adopted this organization as IT service, so moving is currently not logical
