### ISSUE TITLE
Make a distinction between Publishing and Reproducibility

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/workshop-computational-reproducibility#65]
Reproducibility:
- Dependency management
- Environments to run (parts of) your code: Binder, Jupyter notenooks, Knitr

Publishing:
- Licencing
- Archiving
- Publishing

**Comment by nehamoopen** [comment]
For dependency management, we could potentially include an appendix-like chapter with links to other resources like Docker and dependabot? It need not be taught, but it feels like there's so much interesting stuff that should be linked somewhere :P
